version: '3'
services:
  app:
    build: ../app
    ports:
     - "3000:3000"
    networks:
      - proxynet
  reverse-proxy:
    build: ../nginx-sample
    ports:
      - "80:80"
    networks:
      - proxynet
networks:
  proxynet:
    driver: bridge